config/routes.rb
Linkoverload::Application.routes.draw do
  resources :links do
    collection do
      get 'feed'
    end
  end
  
  root :to => 'links#new'
   
  match '/feed' => 'links#feed', 
      :as => :feed,
      :defaults => { :format => 'atom' }
 
  match 'links/feed' => 'links#feed', 
      :as => :feed,
      :defaults => { :format => 'atom' } 
  

 
  

end

app/models/link.rb
class Link < ActiveRecord::Base
	def self.todays_links
		Link.find(:all, :conditions => [" created_at between ? AND ?", Time.zone.now.beginning_of_day, Time.zone.now.end_of_day])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  
  
  def index
    @links = Link.todays_links

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end
  
  def feed
      
      # this will be the name of the feed displayed on the feed reader
      @title = "LinkOverload"

      # the links from today
      @links = Link.todays_links

      # this will be our Feed's update timestamp
      @updated = @links.last.updated_at unless @links.empty?

      respond_to do |format|
        format.atom { render :layout => false }
        # we want the RSS feed to redirect permanently to the ATOM feed
        format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
      end
  end
  

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        flash[:success] = "Successfully Added Link."
        format.html { redirect_to action: "index" }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    flash[:warning] = "Successfully Removed Link."

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= auto_discovery_link_tag :atom, "/feed" %>
    <%= auto_discovery_link_tag :rss, "/feed.rss" %>

    <title>LinkOverload</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "LinkOverload", '/', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   	What's the link?<br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    Why should I click it?<br />
    <%= f.text_area :description, cols: 10, rows: 5 %>
  </div>
  <div class="field">
    Who are you?<br />
    <%= f.text_field :submitter %>
  </div>
  <div class="actions">
    <%= f.submit "Overload!", class: "btn btn-success" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<div class="center">
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<h1>Links from Today</h1>

<table class = 'linktable table well table-bordered table-striped table-condensed'>
  <tr>
    <th>What</th>
    <th>Why</th>
    <th>Who</th>
    <th>When</th>
  

  </tr>

<% @links.each do |link| %>
  <tr>
    <td><%= link_to link.url, link.url, target: "_blank" %></td>
    <td><%= link.description %></td>
    <td><%= link.submitter %></td>
    <td><%= link.created_at %></td>
    <td> <%= link_to 'Remove', link_path(link.id) , method: "delete", class: "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Link', new_link_path, class: "btn btn-large btn-primary"  %>
<%= link_to 'RSS Feed', '/feed',  target: "_blank",  class: "btn btn-small" %>
</div>

app/views/links/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>

<p>
  <b>Submitter:</b>
  <%= @link.submitter %>
</p>

<p>
  <b>Submitted:</b>
  <%= @link.created_at %>
</p>

<p>
  <b>Description:</b>
  <%= @link.description %>
</p>


<%= #link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>